server:
  port: 8080
kafka:
  topic:
    order: order-events
spring:
  kafka:
    bootstarp-servers: localhost:9092
    producer:
      key-serializer: org.apache.kafka.common.serialization.StringSerializer
      value-serializer: org.springframework.kafka.support.serializer.JsonSerializer
eureka:
  client:
    enabled: false